services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_pyflakes
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAIQHWJ4DO6Q4MCT2A
      secret_access_key: 
        secure: mRutnoh3V9uVpK0xUIQKyBc8NcjQwt1xThhcQieI/reYt/zqc2xqGqQA90eU2hahiDFpnz0mr37z2R2PohqGUxkDhjDq9hjnuSwk534UZUR8pFyf+vduR4H+IlZgfzOLHfuMZ0gPHU4F9AeytssLiMZTFvEoP8pCMBjmN+M5T5rCpeT97orBl3x8pyG1Qu+mHC7P9+ID3andRzQ1UZZZcbBapriKD8L9zEKdD7nSk7uM8rpfgGr433EuwkBJjcc8ndjPMUZ5MgwY31xMXg4i0MpqEmIvDH7h0nSRjKsfcxeDdhO1QIzkcTeRj1z7lbllnXcPrHEshZOz96d8/glnuQ3L16zn7ZdqHU/Xgv438Z/ITqqC+e2vJKJ69sooR6NSI/ldodxHWRq1nabA52VMyWkXa6HL21kOke/5aluveIcBSQm5k1Qe8W8+GYJjodWKPO7HoknvuvTPiEts3k0SBcf4n7pfUvW5Hv0zQCocOamOtzrmMQbRIyT9W0tAPtTopPY2XIg2DXXvCRjtdBHnsyOGnM7Gar4rh8eNB0zijppXL47VnSoXFCV09I/SnCHu9ldO8XYkemmfP3qWAMSFIbMGiKVfiRaWu37G0NBd+3qYtf7Zjtr4dVHakOAmyejqkXUI2ovatRxfwrRnIvakWMwMxW0woZJbamcUqfkR70c=
      on:
        repo: FussyFox/pyflakes

