services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_pyflakes
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAUYKBYPB2QY2HG57F
      secret_access_key: 
        secure: "jkfnB26PQ8hOvVA+vU9sOIF5DvOqE6wdpSxWxFy0lSr9fyXNhXvd+aJ/Mw4rLhuJcmEveiDXyabrtXGFRYtJSmjOSn65PrWpCcUGzOuqpIhAsxNqf5DfBKpcE9YFZUbEAU+PMrLI3CQjr24TFH+fXh9eAskO+kFS8C3XBkThunzOz2V7v03medbvAUPDpzmMUmQg6R3+EzIX1C70LzMjrUZ6UUj8Zyj/87pbKAlgE6XCVF4/auoOVfp0K/R9Si2g/FgGRNVIrZHWo9MGK9UKzqFpME4KQOtoQ+b1UuAtOisd6+79qEWXiVg+xLnlGcBal2kFn1PdaNgpiuzqJUJSWYpkiKmPGHx74frGwA8XGLcvrxqnUqDCsuB5M0KRlSwaLdElcIUAjTER87JN1GrYMCXMn+MFLnW4qujPmkBo4li+duUZ7gnBXyt6Hbhv5NcBlSBgEoTKwS+CjyO+pX4sOyuy2zaOqig4yxUIjdvVeqzb0N7unjJ15aRaMUA3A2TnfOkXukOPQiDRCzGdlLwHDeHWbyTLMGNeiOIzPmnmYVMyyr0NxXwU8l6j3xK5xWtfV4L+VJcNn2nlwQ4lmOmLr3QRKCZ14RD8541o191mvmddxUfR5PYq+5bUkQKB8uYutQNo+9FSsX8aEfwL+fn/b/HMO3tckx48BYShKnPhGtA="
      on:
        repo: FussyFox/pyflakes

